name: 'Lint, test, Chromatic release'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint -- --no-fix --max-warnings 0

      - name: Test
        run: npm run test:unit:ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}